server:
  port: 18020
  servlet:    context-path: /data
  

spring:
  application:    name: data-file
  banner:    charset: utf-8
  profiles:
    active:
    - mysql
    - hikari
    - mybatis
    - user
