server:
  port: 18020

  

spring:
  application:    name: data-file
  banner:    charset: utf-8
  profiles:
    active:
    - mysql
    - hikari
    - mybatis
    - user
    - task
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8