# -*- coding: utf-8 -*-
"""
Created on 2022-03-17 17:18:20
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class BooklistItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i booklist
    """

    __table_name__ = "booklist"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.name = None
        self.book_url = None
        self.book_infos = None
        self.author = None
        self.publisher = None
        self.date = None
        self.price = None
        self.rate = None
        self.comment = None
