# -*- coding: utf-8 -*-
"""
Created on 2022-03-18 17:02:24
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class GongshangBaseItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i gongshang_base
    """

    __table_name__ = "gongshang_base"

    def __init__(self, *args, **kwargs):
        self.统一社会信用代码 = None
        self.企业名称 = None
        self.注册号 = None
        self.法定代表人 = None
        self.类型 = None
        self.成立日期 = None
        self.注册资本 = None
        self.核准日期 = None
        self.营业期限自 = None
        self.营业期限至 = None
        self.登记机关 = None
        self.登记状态 = None
        self.住所 = None
        self.经营范围 = None
