# -*- coding: utf-8 -*-
"""
Created on 2022-03-18 14:55:03
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class GongshangListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i gongshang_list
    """

    __table_name__ = "gongshang_list"

    def __init__(self, *args, **kwargs):
        self.notice_id = None  # 			"noticeId": "D2A6E2E4846B94E0E05063A02B0D3859",
        self.notice_date = None  # 			"noticeDate": 1638892800000,
        self.ent_name = None  # 			"entName": "",
        self.datafrom = None  # 			"datafrom": "",
        self.jud_auth = None  # 			"judAuth": "110000",
        self.jud_auth__c_n = None  # 			"judAuth_CN": "北京市市场监督管理局",
        self.jud_date = None  # 			"judDate": null,
        self.last_modified_time = None  # 			"lastModifiedTime": null,
        self.node_num = None  # 			"nodeNum": "110000",
        self.notice_content = None  # 			"noticeContent": "北京康达百安科技有限公司<br/>（统一社会信用代码/注册号：91110114MA01AA5B13）：<br/>&nbsp;&nbsp;&nbsp;&nbsp;经查，你单位因未在工商行政管理部门依照《企业信息公示暂行条例》第十条规定责令的期限内公示有关企业信息的情形被列入经营异常名录届满3年仍未履行相关义务，依据严重违法失信名单管理的有关规定，现决定将你单位列入严重违法失信企业名单，并通过企业信用",
        self.notice_n_o = None  # 			"noticeNO": "",
        self.notice_title = None  # 			"noticeTitle": "关于北京康达百安科技有限公司列入严重违法失信企业名单的决定",
        self.notice_type = None  # 			"noticeType": "21",
        self.simple_cancel_url = None  # 			"simpleCancelUrl": ""
        self.batch_date = None  # 批次时间
        # self.gtime = None  # 抓取时间
