# -*- coding: utf-8 -*-
"""
Created on 2022-04-04 17:00:27
---------
@summary:
---------
@author: wth
"""

from feapder import Item


class 不动产登记中心商品房预售许可Item(Item):
    """
    This class was generated by feapder
    command: feapder create -i 不动产登记中心_商品房预售许可
    """

    __table_name__ = "不动产登记中心_商品房预售许可"

    def __init__(self, *args, **kwargs):
        self.id = None
        self.区域名称 = None
        self.开发企业名称 = None
        self.项目名称 = None
        self.项目地址 = None
        self.项目链接 = None
