# -*- coding: utf-8 -*-
"""
Created on 2022-04-05 17:01:36
---------
@summary:
---------
@author: wth
"""

from feapder import Item


class 不动产登记中心商品房预售房源基本信息Item(Item):
    """
    This class was generated by feapder
    command: feapder create -i 不动产登记中心_商品房预售房源基本信息
    """

    __table_name__ = "不动产登记中心_商品房预售房源基本信息"

    def __init__(self, *args, **kwargs):
        self.id = None
        self.单元 = None
        self.可售 = None  #  
        self.套内面积 = None
        self.建筑面积 = None
        self.房号 = None
        self.房屋用途 = None
        self.房屋类型 = None
        self.房源id = None
        self.楼层 = None
        self.预售价格上限 = None
