
spring:
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123
    url: jdbc:mysql://192.168.0.103:3306/application?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&allowMultiQueries=true
#    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    # SQLException: XAER_INVAL: Invalid arguments (or unsupported command)问题
