spring:
  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.MySQLInnoDBDialect
#        dialect: org.hibernate.dialect.MySQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.OracleDialect
#        dialect: org.hibernate.dialect.SQLServerDialect 
#        dialect: org.hibernate.dialect.DB2Dialect 
#        dialect: org.hibernate.dialect.PostgreSQLDialect


#DB2
#org.hibernate.dialect.DB2Dialect
#DB2 AS/400
#org.hibernate.dialect.DB2400Dialect
#DB2 OS390
#org.hibernate.dialect.DB2390Dialect
#PostgreSQL
#org.hibernate.dialect.PostgreSQLDialect
#MySQL
#org.hibernate.dialect.MySQLDialect
#Oracle (any version)
#org.hibernate.dialect.OracleDialect
#Oracle 9
#org.hibernate.dialect.Oracle9Dialect
#Sybase
#org.hibernate.dialect.SybaseDialect
#Sybase Anywhere
#org.hibernate.dialect.SybaseAnywhereDialect
#Microsoft SQL Server
#org.hibernate.dialect.SQLServerDialect
#SAP DB
#org.hibernate.dialect.SAPDBDialect
#Informix
#org.hibernate.dialect.InformixDialect
#HypersonicSQL
#org.hibernate.dialect.HSQLDialect
#Ingres
#org.hibernate.dialect.IngresDialect
#Progress
#org.hibernate.dialect.ProgressDialect
#Mckoi SQL
#org.hibernate.dialect.MckoiDialect
#Interbase
#org.hibernate.dialect.InterbaseDialect
#Pointbase
#org.hibernate.dialect.PointbaseDialect
#FrontBase
#org.hibernate.dialect.FrontbaseDialect
#Firebird
#org.hibernate.dialect.FirebirdDialect
